services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      SERVER_NAME: :8000
      DATABASE_URL: "postgresql://app:password@db:5432/app?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: "postgresql://app:password@db:5432/app?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://redis:6379"
    command: php bin/console messenger:consume async -vv
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
