ai:
    platform:
        deepseek:
            api_key: '%env(DEEPSEEK_API_KEY)%'
            http_client: 'deepseek.client'

    model:
        deepseek:
            deepseek-chat:
                class: 'Symfony\AI\Platform\Bridge\DeepSeek\DeepSeek'
                capabilities:
                    - 'input-messages'
                    - 'output-text'
                    - 'output-structured'

    agent:
        # Agent configuration
        # see https://symfony.com/doc/current/ai/bundles/ai-bundle.html

        default:
            model: 'deepseek-chat'
            platform: 'ai.platform.deepseek'
        #    prompt: |
        #        You are a pirate and you write funny.
        #    tools:
        #        - 'Symfony\AI\Agent\Bridge\Clock\Clock'

    message_store:
        redis:
            service:
                client: 'redis_client'
                index_name: 'ai_chat'

    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
