doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
            subscription:
                url: '%env(resolve:SUBSCRIPTION_DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                validate_xml_mapping: true
                mappings:
                    User:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/User/Domain/Entity'
                        prefix: 'App\User\Domain\Entity'
                        alias: User
                    Car:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Car/Domain/Entity'
                        prefix: 'App\Car\Domain\Entity'
                        alias: Car
                    AuditLog:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/AuditLog/Domain/Entity'
                        prefix: 'App\AuditLog\Domain\Entity'
                        alias: AuditLog
            subscription:
                connection: subscription
                naming_strategy: doctrine.orm.naming_strategy.underscore
                validate_xml_mapping: true
                mappings:
                    Subscription:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Subscription/Domain/Entity'
                        prefix: 'App\Subscription\Domain\Entity'
                        alias: Subscription


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
